# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# C:\ci\containers\00003dsa76h\tmp\build\80754af9\rsync-recipes\conda-package-handling-1.6.0-vc_14-python_3.7-c_compiler_vs2017-on-winbuilder, last modified Fri Sep 20 15:59:58 2019
# ------------------------------------------------

package:
    name: conda-package-handling
    version: 1.6.0
source:
    fn: conda-package-handling-1.6.0.tar.gz
    sha256: ab3389859be35be6113bc9ce57032fb5a287f699ca2c71ffa470cff6dfd1b542
    url: https://github.com/conda/conda-package-handling/releases/download/1.6.0/conda-package-handling-1.6.0.tar.gz
build:
    entry_points:
        - cph = conda_package_handling.cli:main
    missing_dso_whitelist:
        - '*/VCRUNTIME140.dll'
        - MSVCR90.dll
    number: '0'
    script: C:\ci\conda-package-handling_1569013467814\_h_env\python.exe -m pip install
        . --no-deps -vv
    string: py37h62dcd97_0
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb4161e2_0
        - vswhere 2.7.1 h21ff451_0
    host:
        - _libarchive_static_for_cph 3.3.3 he261513_0
        - ca-certificates 2019.5.15 1
        - certifi 2019.6.16 py37_1
        - cython 0.29.13 py37ha925a31_0
        - openssl 1.1.1d he774522_0
        - pip 19.2.2 py37_0
        - python 3.7.4 h5263a28_0
        - setuptools 41.0.1 py37_0
        - sqlite 3.29.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_0
        - wheel 0.33.4 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
        - six
        - tqdm
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    commands:
        - pytest tests
    imports:
        - conda_package_handling
        - conda_package_handling.archive_utils_cy
    requires:
        - mock
        - pytest
        - pytest-cov
        - pytest-mock
    source_files:
        - tests
about:
    home: https://github.com/conda/conda-package-handling
    license: BSD-3-Clause
    license_family: BSD
    license_file:
        - LICENSE
        - static_deps_licenses/bzip2.txt
        - static_deps_licenses/libarchive.txt
        - static_deps_licenses/zlib.txt
        - static_deps_licenses/zstd.txt
    summary: Create and extract conda packages of various formats
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jjhelmus
        - msarahan
