# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# C:\ci\containers\00001gbdrqp\tmp\build\80754af9\rsync-recipes\pycosat-0.6.3-python_3.7-c_compiler_vs2017-on-winbuilder, last modified Mon Apr 29 07:45:36 2019
# ------------------------------------------------

package:
    name: pycosat
    version: 0.6.3
source:
    git_rev: 0.6.3
    git_url: https://github.com/mingwandroid/pycosat.git
build:
    number: '0'
    string: py37he774522_0
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb8d98e7_1
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2019.11.27 0
        - openssl 1.1.1d he774522_3
        - python 3.7.5 h8c8aaf0_0
        - sqlite 3.30.1 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
    run:
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    files:
        - qg3-08.cnf
        - sudoku.py
        - uf20-098.cnf
    imports:
        - pycosat
about:
    description: 'PicoSAT is a popular SAT solver written by Armin Biere in pure C.
        This

        package provides efficient Python bindings to picosat on the C level, i.e.

        when importing pycosat, the picosat solver becomes part of the Python

        process itself.

        '
    dev_url: https://github.com/ContinuumIO/pycosat
    doc_source_url: https://github.com/ContinuumIO/pycosat/blob/master/README.rst
    doc_url: https://pypi.python.org/pypi/pycosat
    home: https://github.com/ContinuumIO/pycosat
    license: MIT
    summary: Bindings to picosat (a SAT solver)
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - kalefranz
        - mcg1969
        - mingwandroid
        - msarahan
        - nehaljwani
        - pelson
