# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00001gbds9d\tmp\build\80754af9\rsync-recipes\wheel-0.34.2-python_3.7-on-winbuilder, last modified Mon Feb  3 07:44:53 2020
# ------------------------------------------------

package:
    name: wheel
    version: 0.34.2
source:
    sha256: 8788e9155fe14f54164c1b9eb0a319d98ef02c160725587ad60f14ddc57b6f96
    url: https://pypi.io/packages/source/w/wheel/wheel-0.34.2.tar.gz
build:
    entry_points:
        - wheel = wheel.cli:main
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37_0
requirements:
    host:
        - ca-certificates 2020.1.1 0
        - certifi 2019.11.28 py37_0
        - openssl 1.1.1d he774522_3
        - python 3.7.6 h60c2a47_2
        - setuptools 45.1.0 py37_0
        - setuptools_scm 3.4.3 py_0
        - sqlite 3.30.1 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
        - setuptools
test:
    commands:
        - wheel --help
    imports:
        - wheel
about:
    home: https://github.com/pypa/wheel
    license: MIT
    license_file: LICENSE.txt
    summary: A built-package format for Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - ocefpaf
        - pelson
