# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\000020n16k2\tmp\build\80754af9\rsync-recipes\cffi-1.14.0-python_3.7-on-winbuilder, last modified Mon Feb 10 16:14:16 2020
# ------------------------------------------------

package:
    name: cffi
    version: 1.14.0
source:
    patches:
        - 0001-Link-to-dl-library.patch
    sha256: 2d384f4a127a15ba701207f7639d94106693b6cd64173d6c8988e2c25f3ac2b6
    url: https://pypi.io/packages/source/c/cffi/cffi-1.14.0.tar.gz
build:
    number: '0'
    script: C:\ci\cffi_1581351802435\_h_env\python.exe -m pip install . --no-deps
        -vv
    string: py37h7a1dbc1_0
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb8d98e7_1
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2020.1.1 0
        - certifi 2019.11.28 py37_0
        - openssl 1.1.1d he774522_3
        - pip 20.0.2 py37_1
        - pycparser 2.19 py37_0
        - python 3.7.6 h60c2a47_2
        - setuptools 45.1.0 py37_0
        - sqlite 3.31.1 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
        - wheel 0.34.2 py37_0
        - wincertstore 0.2 py37_0
    run:
        - pycparser
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    imports:
        - _cffi_backend
        - cffi
    requires:
        - openssl
about:
    description: 'Cffi aims to allow users to call C code from Python without having
        to

        learn a 3rd language. It provides a convenient and reliable way to call

        compiled C code from Python using interface declarations written in C.

        '
    dev_url: https://bitbucket.org/cffi/cffi/overview
    doc_source_url: https://bitbucket.org/cffi/cffi/src/default/doc/?at=default
    doc_url: http://cffi.readthedocs.org
    home: https://bitbucket.org/cffi/cffi
    license: MIT
    license_file: LICENSE
    summary: Foreign Function Interface for Python calling C code.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - goanpeca
        - inducer
        - mingwandroid
        - ocefpaf
