# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00001nv17k1\tmp\build\80754af9\rsync-recipes\ca-certificates-2020.1.1-on-winbuilder, last modified Thu Jan 30 15:07:58 2020
# ------------------------------------------------

package:
    name: ca-certificates
    version: 2020.1.1
source:
    fn: cacert.pem
    sha256: adf770dfd574a0d6026bfaa270cb6879b063957177a991d453ff1d302c02081f
    url: https://curl.haxx.se/ca/cacert-2020-01-01.pem
build:
    commands:
        - /usr/bin/curl --cacert %LIBRARY_PREFIX%\\ssl\\cacert.pem https://www.google.com
        - if not exist %LIBRARY_PREFIX%\\ssl\\cacert.pem exit 1
        - if not exist %LIBRARY_PREFIX%\\ssl\\cert.pem exit 1
    number: '0'
    string: '0'
about:
    home: https://github.com/conda-forge/ca-certificates-feedstock
    license: MPL 2.0
    license_file: LICENSE.txt
    summary: Certificates for use with other packages.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - msarahan
        - mwcraig
        - ocefpaf
        - patricksnape
        - pelson
        - scopatz
