# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00002gi3rb1\tmp\build\80754af9\rsync-recipes\pip-20.0.2-python_3.7-on-winbuilder, last modified Thu Jan 30 15:03:55 2020
# ------------------------------------------------

package:
    name: pip
    version: 20.0.2
source:
    sha256: 7db0c8ea4c7ea51c8049640e8e6e7fde949de672bfa4949920675563a5a6967f
    url: https://pypi.io/packages/source/p/pip/pip-20.0.2.tar.gz
build:
    disable_pip: true
    entry_points:
        - pip = pip._internal.cli.main:main
    number: '1'
    string: py37_1
requirements:
    host:
        - ca-certificates 2019.11.27 0
        - certifi 2019.11.28 py37_0
        - openssl 1.1.1d he774522_3
        - python 3.7.6 h60c2a47_2
        - setuptools 45.1.0 py37_0
        - sqlite 3.30.1 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
        - setuptools
        - wheel
test:
    commands:
        - pip -h
        - pip list
    imports:
        - pip
about:
    dev_url: https://github.com/pypa/pip
    doc_url: https://pip.pypa.io/en/stable/
    home: https://pip.pypa.io/en/stable/
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: PyPA recommended tool for installing Python packages
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
