# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00001gbdrdb\tmp\build\80754af9\rsync-recipes\pyopenssl-19.1.0-python_3.7-on-winbuilder, last modified Wed Nov 20 08:10:16 2019
# ------------------------------------------------

package:
    name: pyopenssl
    version: 19.1.0
source:
    sha256: 9a24494b2602aaf402be5c9e30a0b82d4a5c67528fe8fb475e3f3bc00dd69507
    url: https://pypi.io/packages/source/p/pyOpenSSL/pyOpenSSL-19.1.0.tar.gz
build:
    number: '0'
    script: C:\ci\pyopenssl_1574265931316\_h_env\python.exe -m pip install . --no-deps
        --ignore-installed --no-cache-dir -vvv
    string: py37_0
requirements:
    host:
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py37_0
        - openssl 1.1.1d he774522_3
        - pip 19.3.1 py37_0
        - python 3.7.5 h8c8aaf0_0
        - setuptools 41.6.0 py37_0
        - sqlite 3.30.1 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_0
        - wheel 0.33.6 py37_0
        - wincertstore 0.2 py37_0
    run:
        - cryptography >=2.8
        - python >=3.7,<3.8.0a0
        - six >=1.5.2
test:
    imports:
        - OpenSSL
        - OpenSSL.SSL
        - OpenSSL.crypto
        - OpenSSL.rand
about:
    description: 'pyOpenSSL is a high-level wrapper around a subset of the OpenSSL
        library.

        It includes:

        -SSL.Connection objects, wrapping the methods of Python''s portable sockets

        -Callbacks written in Python

        -Extensive error-handling mechanism, mirroring OpenSSL''s error codes

        and much more.

        '
    dev_url: https://github.com/pyca/pyopenssl
    doc_source_url: https://github.com/pyca/pyopenssl/blob/master/doc/index.rst
    doc_url: https://pyopenssl.readthedocs.org/en/stable/
    home: https://github.com/pyca/pyopenssl
    license: Apache 2.0
    license_family: Apache
    license_file: LICENSE
    summary: Python wrapper module around the OpenSSL library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - goanpeca
        - mingwandroid
        - nehaljwani
