# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00001nv17a9\tmp\build\80754af9\rsync-recipes\asn1crypto-1.3.0-python_3.7-on-winbuilder, last modified Tue Jan  7 19:56:47 2020
# ------------------------------------------------

package:
    name: asn1crypto
    version: 1.3.0
source:
    sha256: 5a215cb8dc12f892244e3a113fe05397ee23c5c4ca7a69cd6e69811755efc42d
    url: https://pypi.io/packages/source/a/asn1crypto/asn1crypto-1.3.0.tar.gz
build:
    number: '0'
    script: C:\ci\asn1crypto_1578427529167\_h_env\python.exe -m pip install . --no-deps
        --ignore-installed --no-cache-dir -vvv
    string: py37_0
requirements:
    host:
        - ca-certificates 2019.11.27 0
        - certifi 2019.11.28 py37_0
        - openssl 1.1.1d he774522_3
        - pip 19.3.1 py37_0
        - python 3.7.5 h8c8aaf0_0
        - setuptools 44.0.0 py37_0
        - sqlite 3.30.1 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
        - wheel 0.33.6 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - asn1crypto
about:
    home: https://github.com/wbond/asn1crypto
    license: MIT
    license_file: LICENSE
    summary: Python ASN.1 library with a focus on performance and a pythonic API
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jschueller
        - ocefpaf
