# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\000015tu89e\tmp\build\80754af9\rsync-recipes\setuptools-45.2.0-python_3.7-on-winbuilder, last modified Mon Feb 10 16:11:10 2020
# ------------------------------------------------

package:
    name: setuptools
    version: 45.2.0
source:
    patches:
        - 0001-Remove-exact-pinning-on-certifi-and-wincertstore.patch
        - 0002-disable-downloads-inside-conda-build.patch
    sha256: 1cee9d515859e83a409056189bb9f512881bf0fb3334609beed0cf8d384948fc
    url: https://github.com/pypa/setuptools/archive/v45.2.0.tar.gz
build:
    entry_points:
        - easy_install = setuptools.command.easy_install:main
    number: '0'
    string: py37_0
requirements:
    host:
        - ca-certificates 2020.1.1 0
        - certifi 2019.11.28 py37_0
        - openssl 1.1.1d he774522_3
        - python 3.7.6 h60c2a47_2
        - sqlite 3.31.1 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
        - wincertstore 0.2 py37_0
    run:
        - certifi >=2016.9.26
        - python >=3.7,<3.8.0a0
        - wincertstore >=0.2
test:
    commands:
        - easy_install --help
    imports:
        - easy_install
        - pkg_resources
        - setuptools
about:
    description: 'Setuptools is a fully-featured, actively-maintained, and stable
        library

        designed to facilitate packaging Python projects.

        '
    dev_url: https://github.com/pypa/setuptools
    doc_source_url: https://github.com/pypa/setuptools/tree/master/docs
    doc_url: http://pythonhosted.org/setuptools/
    home: https://github.com/pypa/setuptools
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Download, build, install, upgrade, and uninstall Python packages
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - nicoddemus
        - ocefpaf
