# Generated by Django 2.2.10 on 2023-07-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20230716_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
