# Generated by Django 2.2.10 on 2023-07-16 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='Product',
            new_name='product',
        ),
    ]
