# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# C:\ci\containers\00001hbisbg\tmp\build\80754af9\rsync-recipes\chardet-3.0.4-python_3.7-on-winbuilder, last modified Thu Jul 25 08:49:47 2019
# ------------------------------------------------

package:
    name: chardet
    version: 3.0.4
source:
    sha256: 84ab92ed1c4d4f16916e05906b6b75a6c0fb5db821cc65e70cbd64a3e2a5eaae
    url: https://pypi.io/packages/source/c/chardet/chardet-3.0.4.tar.gz
build:
    entry_points:
        - chardetect = chardet.cli.chardetect:main
    number: '1003'
    script: C:\ci\chardet_1564159715080\_h_env\python.exe -m pip install . --no-deps
        --ignore-installed --no-cache-dir -vvv
    string: py37_1003
requirements:
    host:
        - atomicwrites 1.3.0 py37_1
        - attrs 19.1.0 py37_1
        - ca-certificates 2019.5.15 0
        - certifi 2019.6.16 py37_0
        - colorama 0.4.1 py37_0
        - importlib_metadata 0.17 py37_1
        - more-itertools 7.0.0 py37_0
        - openssl 1.1.1c he774522_1
        - packaging 19.0 py37_0
        - pip 19.1.1 py37_0
        - pluggy 0.12.0 py_0
        - py 1.8.0 py37_0
        - pyparsing 2.4.0 py_0
        - pytest 5.0.1 py37_0
        - pytest-runner 4.4 py_0
        - python 3.7.3 h8c8aaf0_1
        - setuptools 41.0.1 py37_0
        - six 1.12.0 py37_0
        - sqlite 3.29.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_4
        - wcwidth 0.1.7 py37_0
        - wheel 0.33.4 py37_0
        - wincertstore 0.2 py37_0
        - zipp 0.5.1 py_0
    run:
        - python >=3.7,<3.8.0a0
test:
    commands:
        - chardetect --help
    imports:
        - chardet
about:
    description: 'chardet is a character encoding auto-detector in Python.

        '
    dev_url: https://github.com/chardet/chardet
    doc_source_url: https://github.com/chardet/chardet/blob/master/docs/index.rst
    doc_url: http://chardet.readthedocs.org/
    home: https://github.com/chardet/chardet
    license: LGPL2
    license_family: GPL
    license_file: LICENSE
    summary: Universal character encoding detector
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dan-blanchard
        - jschueller
        - nehaljwani
        - sigmavirus24
