# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00001gbdrk0\tmp\build\80754af9\rsync-recipes\requests-2.22.0-python_3.7-on-winbuilder, last modified Wed Dec  4 09:42:41 2019
# ------------------------------------------------

package:
    name: requests
    version: 2.22.0
source:
    sha256: 11e007a8a2aa0323f5a921e9e6a2d7e4e67d9877e85773fba9ba6419025cbeb4
    url: https://pypi.io/packages/source/r/requests/requests-2.22.0.tar.gz
build:
    number: '1'
    script: C:\ci\requests_1575481240640\_h_env\python.exe -m pip install . --no-deps
        --ignore-installed -vv
    string: py37_1
requirements:
    host:
        - ca-certificates 2019.11.27 0
        - certifi 2019.11.28 py37_0
        - openssl 1.1.1d he774522_3
        - pip 19.3.1 py37_0
        - python 3.7.5 h8c8aaf0_0
        - setuptools 42.0.2 py37_0
        - sqlite 3.30.1 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_0
        - wheel 0.33.6 py37_0
        - wincertstore 0.2 py37_0
    run:
        - certifi >=2017.4.17
        - chardet >=3.0.2,<3.1.0
        - idna >=2.5,<2.9
        - python >=3.7,<3.8.0a0
        - urllib3 >=1.21.1,<1.26,!=1.25.0,!=1.25.1
test:
    imports:
        - requests
about:
    description: 'Requests is the only Non-GMO HTTP library for Python, safe for human

        consumption.

        '
    dev_url: https://github.com/kennethreitz/requests
    doc_source_url: https://github.com/requests/requests/tree/master/docs
    doc_url: http://docs.python-requests.org/
    home: http://python-requests.org
    license: Apache 2.0
    license_file: LICENSE
    summary: Python HTTP for Humans
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - carlodri
        - jakirkham
        - kalefranz
        - mcg1969
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
        - sigmavirus24
