# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00001gbdril\tmp\build\80754af9\rsync-recipes\certifi-2019.11.28-python_3.7-on-winbuilder, last modified Tue Dec  3 08:16:30 2019
# ------------------------------------------------

package:
    name: certifi
    version: 2019.11.28
source:
    -   folder: certifi
        sha256: 25b64c7da4cd7479594d035c08c2d809eb4aab3a26e5a990ea98cc450c320f1f
        url: https://pypi.io/packages/source/c/certifi/certifi-2019.11.28.tar.gz
    -   folder: pip_wheel
        sha256: 993134f0475471b91452ca029d4390dc8f298ac63a712814f101cd1b6db46676
        url: https://pypi.io/packages/py2.py3/p/pip/pip-19.1.1-py2.py3-none-any.whl
    -   folder: setuptools_wheel
        sha256: c7769ce668c7a333d84e17fe8b524b1c45e7ee9f7908ad0a73e1eda7e6a5aebf
        url: https://pypi.io/packages/py2.py3/s/setuptools/setuptools-41.0.1-py2.py3-none-any.whl
build:
    number: '0'
    string: py37_0
requirements:
    host:
        - ca-certificates 2019.10.16 0
        - openssl 1.1.1d he774522_3
        - python 3.7.5 h8c8aaf0_0
        - sqlite 3.30.1 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_0
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - certifi
about:
    description: 'Certifi is a curated collection of Root Certificates for validating
        the

        trustworthiness of SSL certificates while verifying the identity of TLS

        hosts.

        '
    dev_url: https://github.com/certifi/python-certifi
    doc_source_url: https://github.com/certifi/certifi.io/blob/master/README.rst
    doc_url: https://pypi.python.org/pypi/certifi
    home: http://certifi.io/
    license: ISC
    license_file: certifi/LICENSE
    summary: Python package for providing Mozilla's CA Bundle.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - ocefpaf
        - pelson
        - sigmavirus24
