# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# C:\Users\builder\msarahan\aggregate\pywin32-feedstock\recipe, last modified Wed Jan 15 09:23:51 2020
# ------------------------------------------------

package:
    name: pywin32
    version: '227'
source:
    fn: pywin32-227.zip
    patches:
        - 0001-scintilla-makefiles.patch
        - 0002-nuke-post-install.patch
        - 0003-remove-PATH-pth-hack.patch
        - 0004-remove-JOB_OBJECT_RESERVED_LIMIT_VALID_FLAGS.patch
    sha256: f82946fb29d55a27b3abcd0b527ef2e8da6ea05b01dfcc40bfc14847b7673e8e
    url: https://github.com/mhammond/pywin32/archive/b227.zip
build:
    number: '1'
    string: py37he774522_1
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb8d98e7_1
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2019.11.27 0
        - certifi 2019.11.28 py37_0
        - openssl 1.1.1d he774522_3
        - pip 19.3.1 py37_0
        - python 3.7.6 h60c2a47_2
        - setuptools 44.0.0 py37_0
        - sqlite 3.30.1 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
        - wheel 0.33.6 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
about:
    description: 'A set of extension modules that provides access to many of the Windows
        API functions.

        '
    doc_source_url: https://sourceforge.net/projects/pywin32/
    doc_url: https://pypi.python.org/pypi/pywin32
    home: https://sourceforge.net/projects/pywin32
    license: PSF
    summary: Python extensions for Windows
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mingwandroid
        - nicoddemus
