# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# C:\ci\containers\00003dsa781\tmp\build\80754af9\rsync-recipes\pysocks-1.7.1-python_3.7-on-winbuilder, last modified Mon Sep 23 13:35:58 2019
# ------------------------------------------------

package:
    name: pysocks
    version: 1.7.1
source:
    sha256: 3f8804571ebe159c380ac6de37643bb4685970655d3bba243530d6558b799aa0
    url: https://pypi.io/packages/source/P/PySocks/PySocks-1.7.1.tar.gz
build:
    number: '0'
    script: C:\ci\pysocks_1569264591804\_h_env\python.exe -m pip install . --no-deps
        -vv
    string: py37_0
requirements:
    host:
        - ca-certificates 2019.5.15 1
        - certifi 2019.9.11 py37_0
        - openssl 1.1.1d he774522_0
        - pip 19.2.2 py37_0
        - python 3.7.4 h5263a28_0
        - setuptools 41.2.0 py37_0
        - sqlite 3.29.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_0
        - wheel 0.33.4 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
        - win_inet_pton
test:
    imports:
        - socks
about:
    dev_url: https://github.com/Anorov/PySocks
    doc_url: https://github.com/Anorov/PySocks/blob/master/README.md
    home: https://github.com/Anorov/PySocks
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: A Python SOCKS client module. See https://github.com/Anorov/PySocks for
        more information.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - pmlandwehr
